// Authoritative Uttar Pradesh districts + Vidhan Sabha constituencies.
// Source: Wikipedia (List of districts of Uttar Pradesh; List of constituencies of the UP Legislative Assembly).

export interface UpDistrict {
  name: string;
  division: string;
}

export interface UpConstituency {
  number: number; // AC number (1-403)
  name: string; // canonical English name
  district: string; // must match a district name exactly
  reserved?: 'SC' | 'ST'; // if the seat is reserved
}

export const UP_DISTRICTS: UpDistrict[] = [
  // Agra Division
  { name: 'Agra', division: 'Agra' },
  { name: 'Firozabad', division: 'Agra' },
  { name: 'Mainpuri', division: 'Agra' },
  { name: 'Mathura', division: 'Agra' },
  // Aligarh Division
  { name: 'Aligarh', division: 'Aligarh' },
  { name: 'Etah', division: 'Aligarh' },
  { name: 'Hathras', division: 'Aligarh' },
  { name: 'Kasganj', division: 'Aligarh' },
  // Ayodhya Division
  { name: 'Ambedkar Nagar', division: 'Ayodhya' },
  { name: 'Amethi', division: 'Ayodhya' },
  { name: 'Ayodhya', division: 'Ayodhya' },
  { name: 'Barabanki', division: 'Ayodhya' },
  { name: 'Sultanpur', division: 'Ayodhya' },
  // Azamgarh Division
  { name: 'Azamgarh', division: 'Azamgarh' },
  { name: 'Ballia', division: 'Azamgarh' },
  { name: 'Mau', division: 'Azamgarh' },
  // Bareilly Division
  { name: 'Bareilly', division: 'Bareilly' },
  { name: 'Budaun', division: 'Bareilly' },
  { name: 'Pilibhit', division: 'Bareilly' },
  { name: 'Shahjahanpur', division: 'Bareilly' },
  // Basti Division
  { name: 'Basti', division: 'Basti' },
  { name: 'Sant Kabir Nagar', division: 'Basti' },
  { name: 'Siddharthnagar', division: 'Basti' },
  // Chitrakoot Division
  { name: 'Banda', division: 'Chitrakoot' },
  { name: 'Chitrakoot', division: 'Chitrakoot' },
  { name: 'Hamirpur', division: 'Chitrakoot' },
  { name: 'Mahoba', division: 'Chitrakoot' },
  // Devipatan Division
  { name: 'Bahraich', division: 'Devipatan' },
  { name: 'Balrampur', division: 'Devipatan' },
  { name: 'Gonda', division: 'Devipatan' },
  { name: 'Shravasti', division: 'Devipatan' },
  // Gorakhpur Division
  { name: 'Deoria', division: 'Gorakhpur' },
  { name: 'Gorakhpur', division: 'Gorakhpur' },
  { name: 'Kushinagar', division: 'Gorakhpur' },
  { name: 'Maharajganj', division: 'Gorakhpur' },
  // Jhansi Division
  { name: 'Jalaun', division: 'Jhansi' },
  { name: 'Jhansi', division: 'Jhansi' },
  { name: 'Lalitpur', division: 'Jhansi' },
  // Kanpur Division
  { name: 'Auraiya', division: 'Kanpur' },
  { name: 'Etawah', division: 'Kanpur' },
  { name: 'Farrukhabad', division: 'Kanpur' },
  { name: 'Kannauj', division: 'Kanpur' },
  { name: 'Kanpur Nagar', division: 'Kanpur' },
  { name: 'Kanpur Dehat', division: 'Kanpur' },
  // Lucknow Division
  { name: 'Hardoi', division: 'Lucknow' },
  { name: 'Lakhimpur Kheri', division: 'Lucknow' },
  { name: 'Lucknow', division: 'Lucknow' },
  { name: 'Raebareli', division: 'Lucknow' },
  { name: 'Sitapur', division: 'Lucknow' },
  { name: 'Unnao', division: 'Lucknow' },
  // Meerut Division
  { name: 'Bagpat', division: 'Meerut' },
  { name: 'Bulandshahr', division: 'Meerut' },
  { name: 'Gautam Buddha Nagar', division: 'Meerut' },
  { name: 'Ghaziabad', division: 'Meerut' },
  { name: 'Hapur', division: 'Meerut' },
  { name: 'Meerut', division: 'Meerut' },
  // Mirzapur Division
  { name: 'Bhadohi', division: 'Mirzapur' },
  { name: 'Mirzapur', division: 'Mirzapur' },
  { name: 'Sonbhadra', division: 'Mirzapur' },
  // Moradabad Division
  { name: 'Amroha', division: 'Moradabad' },
  { name: 'Bijnor', division: 'Moradabad' },
  { name: 'Moradabad', division: 'Moradabad' },
  { name: 'Rampur', division: 'Moradabad' },
  { name: 'Sambhal', division: 'Moradabad' },
  // Prayagraj Division
  { name: 'Fatehpur', division: 'Prayagraj' },
  { name: 'Kaushambi', division: 'Prayagraj' },
  { name: 'Pratapgarh', division: 'Prayagraj' },
  { name: 'Prayagraj', division: 'Prayagraj' },
  // Saharanpur Division
  { name: 'Muzaffarnagar', division: 'Saharanpur' },
  { name: 'Saharanpur', division: 'Saharanpur' },
  { name: 'Shamli', division: 'Saharanpur' },
  // Varanasi Division
  { name: 'Chandauli', division: 'Varanasi' },
  { name: 'Ghazipur', division: 'Varanasi' },
  { name: 'Jaunpur', division: 'Varanasi' },
  { name: 'Varanasi', division: 'Varanasi' },
];

export const UP_CONSTITUENCIES: UpConstituency[] = [
  { number: 1, name: 'Behat', district: 'Saharanpur' },
  { number: 2, name: 'Nakur', district: 'Saharanpur' },
  { number: 3, name: 'Saharanpur Nagar', district: 'Saharanpur' },
  { number: 4, name: 'Saharanpur', district: 'Saharanpur' },
  { number: 5, name: 'Deoband', district: 'Saharanpur' },
  { number: 6, name: 'Rampur Maniharan', district: 'Saharanpur', reserved: 'SC' },
  { number: 7, name: 'Gangoh', district: 'Shamli' },
  { number: 8, name: 'Kairana', district: 'Shamli' },
  { number: 9, name: 'Thana Bhawan', district: 'Shamli' },
  { number: 10, name: 'Shamli', district: 'Shamli' },
  { number: 11, name: 'Budhana', district: 'Muzaffarnagar' },
  { number: 12, name: 'Charthawal', district: 'Muzaffarnagar' },
  { number: 13, name: 'Purqazi', district: 'Muzaffarnagar', reserved: 'SC' },
  { number: 14, name: 'Muzaffarnagar', district: 'Muzaffarnagar' },
  { number: 15, name: 'Khatauli', district: 'Muzaffarnagar' },
  { number: 16, name: 'Meerapur', district: 'Muzaffarnagar' },
  { number: 17, name: 'Najibabad', district: 'Bijnor' },
  { number: 18, name: 'Nagina', district: 'Bijnor', reserved: 'SC' },
  { number: 19, name: 'Barhapur', district: 'Bijnor' },
  { number: 20, name: 'Dhampur', district: 'Bijnor' },
  { number: 21, name: 'Nehtaur', district: 'Bijnor', reserved: 'SC' },
  { number: 22, name: 'Bijnor', district: 'Bijnor' },
  { number: 23, name: 'Chandpur', district: 'Bijnor' },
  { number: 24, name: 'Noorpur', district: 'Bijnor' },
  { number: 25, name: 'Kanth', district: 'Moradabad' },
  { number: 26, name: 'Thakurdwara', district: 'Moradabad' },
  { number: 27, name: 'Moradabad Rural', district: 'Moradabad' },
  { number: 28, name: 'Moradabad Nagar', district: 'Moradabad' },
  { number: 29, name: 'Kundarki', district: 'Sambhal' },
  { number: 30, name: 'Bilari', district: 'Sambhal' },
  { number: 31, name: 'Chandausi', district: 'Sambhal', reserved: 'SC' },
  { number: 32, name: 'Asmoli', district: 'Sambhal' },
  { number: 33, name: 'Sambhal', district: 'Sambhal' },
  { number: 34, name: 'Suar', district: 'Rampur' },
  { number: 35, name: 'Chamraua', district: 'Rampur' },
  { number: 36, name: 'Bilaspur', district: 'Rampur' },
  { number: 37, name: 'Rampur', district: 'Rampur' },
  { number: 38, name: 'Milak', district: 'Rampur', reserved: 'SC' },
  { number: 39, name: 'Dhanaura', district: 'Amroha', reserved: 'SC' },
  { number: 40, name: 'Naugawan Sadat', district: 'Amroha' },
  { number: 41, name: 'Amroha', district: 'Amroha' },
  { number: 42, name: 'Hasanpur', district: 'Amroha' },
  { number: 43, name: 'Siwalkhas', district: 'Meerut' },
  { number: 44, name: 'Sardhana', district: 'Meerut' },
  { number: 45, name: 'Hastinapur', district: 'Meerut', reserved: 'SC' },
  { number: 46, name: 'Kithore', district: 'Meerut' },
  { number: 47, name: 'Meerut Cantt.', district: 'Meerut' },
  { number: 48, name: 'Meerut', district: 'Meerut' },
  { number: 49, name: 'Meerut South', district: 'Meerut' },
  { number: 50, name: 'Chhaprauli', district: 'Bagpat' },
  { number: 51, name: 'Baraut', district: 'Bagpat' },
  { number: 52, name: 'Bagpat', district: 'Bagpat' },
  { number: 53, name: 'Loni', district: 'Ghaziabad' },
  { number: 54, name: 'Muradnagar', district: 'Ghaziabad' },
  { number: 55, name: 'Sahibabad', district: 'Ghaziabad' },
  { number: 56, name: 'Ghaziabad', district: 'Ghaziabad' },
  { number: 57, name: 'Modinagar', district: 'Ghaziabad' },
  { number: 58, name: 'Dhaulana', district: 'Hapur' },
  { number: 59, name: 'Hapur', district: 'Hapur', reserved: 'SC' },
  { number: 60, name: 'Garhmukteshwar', district: 'Hapur' },
  { number: 61, name: 'Noida', district: 'Gautam Buddha Nagar' },
  { number: 62, name: 'Dadri', district: 'Gautam Buddha Nagar' },
  { number: 63, name: 'Jewar', district: 'Gautam Buddha Nagar' },
  { number: 64, name: 'Sikandrabad', district: 'Bulandshahr' },
  { number: 65, name: 'Bulandshahr', district: 'Bulandshahr' },
  { number: 66, name: 'Syana', district: 'Bulandshahr' },
  { number: 67, name: 'Anupshahr', district: 'Bulandshahr' },
  { number: 68, name: 'Debai', district: 'Bulandshahr' },
  { number: 69, name: 'Shikarpur', district: 'Bulandshahr' },
  { number: 70, name: 'Khurja', district: 'Bulandshahr', reserved: 'SC' },
  { number: 71, name: 'Khair', district: 'Aligarh', reserved: 'SC' },
  { number: 72, name: 'Barauli', district: 'Aligarh' },
  { number: 73, name: 'Atrauli', district: 'Aligarh' },
  { number: 74, name: 'Chharra', district: 'Aligarh' },
  { number: 75, name: 'Koil', district: 'Aligarh' },
  { number: 76, name: 'Aligarh', district: 'Aligarh' },
  { number: 77, name: 'Iglas', district: 'Aligarh', reserved: 'SC' },
  { number: 78, name: 'Hathras', district: 'Hathras', reserved: 'SC' },
  { number: 79, name: 'Sadabad', district: 'Hathras' },
  { number: 80, name: 'Sikandra Rao', district: 'Hathras' },
  { number: 81, name: 'Chhata', district: 'Mathura' },
  { number: 82, name: 'Mant', district: 'Mathura' },
  { number: 83, name: 'Goverdhan', district: 'Mathura' },
  { number: 84, name: 'Mathura', district: 'Mathura' },
  { number: 85, name: 'Baldev', district: 'Mathura', reserved: 'SC' },
  { number: 86, name: 'Etmadpur', district: 'Agra' },
  { number: 87, name: 'Agra Cantt.', district: 'Agra', reserved: 'SC' },
  { number: 88, name: 'Agra South', district: 'Agra' },
  { number: 89, name: 'Agra North', district: 'Agra' },
  { number: 90, name: 'Agra Rural', district: 'Agra', reserved: 'SC' },
  { number: 91, name: 'Fatehpur Sikri', district: 'Agra' },
  { number: 92, name: 'Kheragarh', district: 'Agra' },
  { number: 93, name: 'Fatehabad', district: 'Agra' },
  { number: 94, name: 'Bah', district: 'Agra' },
  { number: 95, name: 'Tundla', district: 'Firozabad', reserved: 'SC' },
  { number: 96, name: 'Jasrana', district: 'Firozabad' },
  { number: 97, name: 'Firozabad', district: 'Firozabad' },
  { number: 98, name: 'Shikohabad', district: 'Firozabad' },
  { number: 99, name: 'Sirsaganj', district: 'Firozabad' },
  { number: 100, name: 'Kasganj', district: 'Kasganj' },
  { number: 101, name: 'Amanpur', district: 'Kasganj' },
  { number: 102, name: 'Patiyali', district: 'Kasganj' },
  { number: 103, name: 'Aliganj', district: 'Etah' },
  { number: 104, name: 'Etah', district: 'Etah' },
  { number: 105, name: 'Marhara', district: 'Etah' },
  { number: 106, name: 'Jalesar', district: 'Etah', reserved: 'SC' },
  { number: 107, name: 'Mainpuri', district: 'Mainpuri' },
  { number: 108, name: 'Bhongaon', district: 'Mainpuri' },
  { number: 109, name: 'Kishni', district: 'Mainpuri', reserved: 'SC' },
  { number: 110, name: 'Karhal', district: 'Mainpuri' },
  { number: 111, name: 'Gunnaur', district: 'Sambhal' },
  { number: 112, name: 'Bisauli', district: 'Budaun', reserved: 'SC' },
  { number: 113, name: 'Sahaswan', district: 'Budaun' },
  { number: 114, name: 'Bilsi', district: 'Budaun' },
  { number: 115, name: 'Badaun', district: 'Budaun' },
  { number: 116, name: 'Shekhupur', district: 'Budaun' },
  { number: 117, name: 'Dataganj', district: 'Budaun' },
  { number: 118, name: 'Baheri', district: 'Bareilly' },
  { number: 119, name: 'Meerganj', district: 'Bareilly' },
  { number: 120, name: 'Bhojipura', district: 'Bareilly' },
  { number: 121, name: 'Nawabganj', district: 'Bareilly' },
  { number: 122, name: 'Faridpur', district: 'Bareilly', reserved: 'SC' },
  { number: 123, name: 'Bithari Chainpur', district: 'Bareilly' },
  { number: 124, name: 'Bareilly', district: 'Bareilly' },
  { number: 125, name: 'Bareilly Cantt.', district: 'Bareilly' },
  { number: 126, name: 'Aonla', district: 'Bareilly' },
  { number: 127, name: 'Pilibhit', district: 'Pilibhit' },
  { number: 128, name: 'Barkhera', district: 'Pilibhit' },
  { number: 129, name: 'Puranpur', district: 'Pilibhit', reserved: 'SC' },
  { number: 130, name: 'Bisalpur', district: 'Pilibhit' },
  { number: 131, name: 'Katra', district: 'Shahjahanpur' },
  { number: 132, name: 'Jalalabad', district: 'Shahjahanpur' },
  { number: 133, name: 'Tilhar', district: 'Shahjahanpur' },
  { number: 134, name: 'Powayan', district: 'Shahjahanpur', reserved: 'SC' },
  { number: 135, name: 'Shahjahanpur', district: 'Shahjahanpur' },
  { number: 136, name: 'Dadraul', district: 'Shahjahanpur' },
  { number: 137, name: 'Palia', district: 'Lakhimpur Kheri' },
  { number: 138, name: 'Nighasan', district: 'Lakhimpur Kheri' },
  { number: 139, name: 'Gola Gokrannath', district: 'Lakhimpur Kheri' },
  { number: 140, name: 'Sri Nagar', district: 'Lakhimpur Kheri', reserved: 'SC' },
  { number: 141, name: 'Dhaurahra', district: 'Lakhimpur Kheri' },
  { number: 142, name: 'Lakhimpur', district: 'Lakhimpur Kheri' },
  { number: 143, name: 'Kasta', district: 'Lakhimpur Kheri', reserved: 'SC' },
  { number: 144, name: 'Mohammdi', district: 'Lakhimpur Kheri' },
  { number: 145, name: 'Maholi', district: 'Sitapur' },
  { number: 146, name: 'Sitapur', district: 'Sitapur' },
  { number: 147, name: 'Hargaon', district: 'Sitapur', reserved: 'SC' },
  { number: 148, name: 'Laharpur', district: 'Sitapur' },
  { number: 149, name: 'Biswan', district: 'Sitapur' },
  { number: 150, name: 'Sevata', district: 'Sitapur' },
  { number: 151, name: 'Mahmoodabad', district: 'Sitapur' },
  { number: 152, name: 'Sidhauli', district: 'Sitapur', reserved: 'SC' },
  { number: 153, name: 'Misrikh', district: 'Sitapur', reserved: 'SC' },
  { number: 154, name: 'Sawayazpur', district: 'Hardoi' },
  { number: 155, name: 'Shahabad', district: 'Hardoi' },
  { number: 156, name: 'Hardoi', district: 'Hardoi' },
  { number: 157, name: 'Gopamau', district: 'Hardoi', reserved: 'SC' },
  { number: 158, name: 'Sandi', district: 'Hardoi', reserved: 'SC' },
  { number: 159, name: 'Bilgram-Mallanwan', district: 'Hardoi' },
  { number: 160, name: 'Balamau', district: 'Hardoi', reserved: 'SC' },
  { number: 161, name: 'Sandila', district: 'Hardoi' },
  { number: 162, name: 'Bangarmau', district: 'Unnao' },
  { number: 163, name: 'Safipur', district: 'Unnao', reserved: 'SC' },
  { number: 164, name: 'Mohan', district: 'Unnao', reserved: 'SC' },
  { number: 165, name: 'Unnao', district: 'Unnao' },
  { number: 166, name: 'Bhagwantnagar', district: 'Unnao' },
  { number: 167, name: 'Purwa', district: 'Unnao' },
  { number: 168, name: 'Malihabad', district: 'Lucknow', reserved: 'SC' },
  { number: 169, name: 'Bakshi Kaa Talab', district: 'Lucknow' },
  { number: 170, name: 'Sarojini Nagar', district: 'Lucknow' },
  { number: 171, name: 'Lucknow West', district: 'Lucknow' },
  { number: 172, name: 'Lucknow North', district: 'Lucknow' },
  { number: 173, name: 'Lucknow East', district: 'Lucknow' },
  { number: 174, name: 'Lucknow Central', district: 'Lucknow' },
  { number: 175, name: 'Lucknow Cantonment', district: 'Lucknow' },
  { number: 176, name: 'Mohanlalganj', district: 'Lucknow', reserved: 'SC' },
  { number: 177, name: 'Bachhrawan', district: 'Raebareli', reserved: 'SC' },
  { number: 178, name: 'Tiloi', district: 'Amethi' },
  { number: 179, name: 'Harchandpur', district: 'Raebareli' },
  { number: 180, name: 'Rae Bareli', district: 'Raebareli' },
  { number: 181, name: 'Salon', district: 'Raebareli', reserved: 'SC' },
  { number: 182, name: 'Sareni', district: 'Raebareli' },
  { number: 183, name: 'Unchahar', district: 'Raebareli' },
  { number: 184, name: 'Jagdishpur', district: 'Amethi', reserved: 'SC' },
  { number: 185, name: 'Gauriganj', district: 'Amethi' },
  { number: 186, name: 'Amethi', district: 'Amethi' },
  { number: 187, name: 'Isauli', district: 'Sultanpur' },
  { number: 188, name: 'Sultanpur', district: 'Sultanpur' },
  { number: 189, name: 'Sadar', district: 'Sultanpur' },
  { number: 190, name: 'Lambhua', district: 'Sultanpur' },
  { number: 191, name: 'Kadipur', district: 'Sultanpur', reserved: 'SC' },
  { number: 192, name: 'Kaimganj', district: 'Farrukhabad', reserved: 'SC' },
  { number: 193, name: 'Amritpur', district: 'Farrukhabad' },
  { number: 194, name: 'Farrukhabad', district: 'Farrukhabad' },
  { number: 195, name: 'Bhojpur', district: 'Farrukhabad' },
  { number: 196, name: 'Chhibramau', district: 'Kannauj' },
  { number: 197, name: 'Tirwa', district: 'Kannauj' },
  { number: 198, name: 'Kannauj', district: 'Kannauj', reserved: 'SC' },
  { number: 199, name: 'Jaswantnagar', district: 'Etawah' },
  { number: 200, name: 'Etawah', district: 'Etawah' },
  { number: 201, name: 'Bharthana', district: 'Etawah', reserved: 'SC' },
  { number: 202, name: 'Bidhuna', district: 'Auraiya' },
  { number: 203, name: 'Dibiyapur', district: 'Auraiya' },
  { number: 204, name: 'Auraiya', district: 'Auraiya', reserved: 'SC' },
  { number: 205, name: 'Rasulabad', district: 'Kanpur Dehat', reserved: 'SC' },
  { number: 206, name: 'Akbarpur-Raniya', district: 'Kanpur Dehat' },
  { number: 207, name: 'Sikandra', district: 'Kanpur Dehat' },
  { number: 208, name: 'Bhognipur', district: 'Kanpur Dehat' },
  { number: 209, name: 'Bilhaur', district: 'Kanpur Nagar', reserved: 'SC' },
  { number: 210, name: 'Bithoor', district: 'Kanpur Nagar' },
  { number: 211, name: 'Kalyanpur', district: 'Kanpur Nagar' },
  { number: 212, name: 'Govind Nagar', district: 'Kanpur Nagar' },
  { number: 213, name: 'Sishamau', district: 'Kanpur Nagar' },
  { number: 214, name: 'Arya Nagar', district: 'Kanpur Nagar' },
  { number: 215, name: 'Kidwai Nagar', district: 'Kanpur Nagar' },
  { number: 216, name: 'Kanpur Cantonment', district: 'Kanpur Nagar' },
  { number: 217, name: 'Maharajpur', district: 'Kanpur Nagar' },
  { number: 218, name: 'Ghatampur', district: 'Kanpur Nagar', reserved: 'SC' },
  { number: 219, name: 'Madhogarh', district: 'Jalaun' },
  { number: 220, name: 'Kalpi', district: 'Jalaun' },
  { number: 221, name: 'Orai', district: 'Jalaun', reserved: 'SC' },
  { number: 222, name: 'Babina', district: 'Jhansi' },
  { number: 223, name: 'Jhansi Nagar', district: 'Jhansi' },
  { number: 224, name: 'Mauranipur', district: 'Jhansi', reserved: 'SC' },
  { number: 225, name: 'Garautha', district: 'Jhansi' },
  { number: 226, name: 'Lalitpur', district: 'Lalitpur' },
  { number: 227, name: 'Mehroni', district: 'Lalitpur', reserved: 'SC' },
  { number: 228, name: 'Hamirpur', district: 'Hamirpur' },
  { number: 229, name: 'Rath', district: 'Hamirpur', reserved: 'SC' },
  { number: 230, name: 'Mahoba', district: 'Mahoba' },
  { number: 231, name: 'Charkhari', district: 'Mahoba' },
  { number: 232, name: 'Tindwari', district: 'Banda' },
  { number: 233, name: 'Baberu', district: 'Banda' },
  { number: 234, name: 'Naraini', district: 'Banda', reserved: 'SC' },
  { number: 235, name: 'Banda', district: 'Banda' },
  { number: 236, name: 'Chitrakoot', district: 'Chitrakoot' },
  { number: 237, name: 'Manikpur', district: 'Chitrakoot' },
  { number: 238, name: 'Jahanabad', district: 'Fatehpur' },
  { number: 239, name: 'Bindki', district: 'Fatehpur' },
  { number: 240, name: 'Fatehpur', district: 'Fatehpur' },
  { number: 241, name: 'Ayah Shah', district: 'Fatehpur' },
  { number: 242, name: 'Husainganj', district: 'Fatehpur' },
  { number: 243, name: 'Khaga', district: 'Fatehpur', reserved: 'SC' },
  { number: 244, name: 'Rampur Khas', district: 'Pratapgarh' },
  { number: 245, name: 'Babaganj', district: 'Pratapgarh', reserved: 'SC' },
  { number: 246, name: 'Kunda', district: 'Pratapgarh' },
  { number: 247, name: 'Vishwanathganj', district: 'Pratapgarh' },
  { number: 248, name: 'Pratapgarh', district: 'Pratapgarh' },
  { number: 249, name: 'Patti', district: 'Pratapgarh' },
  { number: 250, name: 'Raniganj', district: 'Pratapgarh' },
  { number: 251, name: 'Sirathu', district: 'Kaushambi' },
  { number: 252, name: 'Manjhanpur', district: 'Kaushambi', reserved: 'SC' },
  { number: 253, name: 'Chail', district: 'Kaushambi' },
  { number: 254, name: 'Phaphamau', district: 'Prayagraj' },
  { number: 255, name: 'Soraon', district: 'Prayagraj', reserved: 'SC' },
  { number: 256, name: 'Phulpur', district: 'Prayagraj' },
  { number: 257, name: 'Pratappur', district: 'Prayagraj' },
  { number: 258, name: 'Handia', district: 'Prayagraj' },
  { number: 259, name: 'Meja', district: 'Prayagraj' },
  { number: 260, name: 'Karachhana', district: 'Prayagraj' },
  { number: 261, name: 'Prayagraj West', district: 'Prayagraj' },
  { number: 262, name: 'Prayagraj North', district: 'Prayagraj' },
  { number: 263, name: 'Prayagraj South', district: 'Prayagraj' },
  { number: 264, name: 'Bara', district: 'Prayagraj', reserved: 'SC' },
  { number: 265, name: 'Koraon', district: 'Prayagraj', reserved: 'SC' },
  { number: 266, name: 'Kursi', district: 'Barabanki' },
  { number: 267, name: 'Ram Nagar', district: 'Barabanki' },
  { number: 268, name: 'Barabanki', district: 'Barabanki' },
  { number: 269, name: 'Zaidpur', district: 'Barabanki', reserved: 'SC' },
  { number: 270, name: 'Dariyabad', district: 'Barabanki' },
  { number: 271, name: 'Rudauli', district: 'Ayodhya' },
  { number: 272, name: 'Haidergarh', district: 'Barabanki', reserved: 'SC' },
  { number: 273, name: 'Milkipur', district: 'Ayodhya', reserved: 'SC' },
  { number: 274, name: 'Bikapur', district: 'Ayodhya' },
  { number: 275, name: 'Ayodhya', district: 'Ayodhya' },
  { number: 276, name: 'Goshainganj', district: 'Ayodhya' },
  { number: 277, name: 'Katehari', district: 'Ambedkar Nagar' },
  { number: 278, name: 'Tanda', district: 'Ambedkar Nagar' },
  { number: 279, name: 'Alapur', district: 'Ambedkar Nagar', reserved: 'SC' },
  { number: 280, name: 'Jalalpur', district: 'Ambedkar Nagar' },
  { number: 281, name: 'Akbarpur', district: 'Ambedkar Nagar' },
  { number: 282, name: 'Balha', district: 'Bahraich', reserved: 'SC' },
  { number: 283, name: 'Nanpara', district: 'Bahraich' },
  { number: 284, name: 'Matera', district: 'Bahraich' },
  { number: 285, name: 'Mahasi', district: 'Bahraich' },
  { number: 286, name: 'Bahraich', district: 'Bahraich' },
  { number: 287, name: 'Payagpur', district: 'Bahraich' },
  { number: 288, name: 'Kaiserganj', district: 'Bahraich' },
  { number: 289, name: 'Bhinga', district: 'Shravasti' },
  { number: 290, name: 'Shrawasti', district: 'Shravasti' },
  { number: 291, name: 'Tulsipur', district: 'Balrampur' },
  { number: 292, name: 'Gainsari', district: 'Balrampur' },
  { number: 293, name: 'Utraula', district: 'Balrampur' },
  { number: 294, name: 'Balrampur', district: 'Balrampur', reserved: 'SC' },
  { number: 295, name: 'Mehnaun', district: 'Gonda' },
  { number: 296, name: 'Gonda', district: 'Gonda' },
  { number: 297, name: 'Katra Bazar', district: 'Gonda' },
  { number: 298, name: 'Colonelganj', district: 'Gonda' },
  { number: 299, name: 'Tarabganj', district: 'Gonda' },
  { number: 300, name: 'Mankapur', district: 'Gonda', reserved: 'SC' },
  { number: 301, name: 'Gaura', district: 'Gonda' },
  { number: 302, name: 'Shohratgarh', district: 'Siddharthnagar' },
  { number: 303, name: 'Kapilvastu', district: 'Siddharthnagar', reserved: 'SC' },
  { number: 304, name: 'Bansi', district: 'Siddharthnagar' },
  { number: 305, name: 'Itwa', district: 'Siddharthnagar' },
  { number: 306, name: 'Domariyaganj', district: 'Siddharthnagar' },
  { number: 307, name: 'Harraiya', district: 'Basti' },
  { number: 308, name: 'Kaptanganj', district: 'Basti' },
  { number: 309, name: 'Rudhauli', district: 'Basti' },
  { number: 310, name: 'Basti Sadar', district: 'Basti' },
  { number: 311, name: 'Mahadewa', district: 'Basti', reserved: 'SC' },
  { number: 312, name: 'Menhdawal', district: 'Sant Kabir Nagar' },
  { number: 313, name: 'Khalilabad', district: 'Sant Kabir Nagar' },
  { number: 314, name: 'Dhanghata', district: 'Sant Kabir Nagar', reserved: 'SC' },
  { number: 315, name: 'Pharenda', district: 'Maharajganj' },
  { number: 316, name: 'Nautanwa', district: 'Maharajganj' },
  { number: 317, name: 'Siswa', district: 'Maharajganj' },
  { number: 318, name: 'Maharajganj', district: 'Maharajganj', reserved: 'SC' },
  { number: 319, name: 'Paniyara', district: 'Maharajganj' },
  { number: 320, name: 'Caimpiyarganj', district: 'Gorakhpur' },
  { number: 321, name: 'Pipraich', district: 'Gorakhpur' },
  { number: 322, name: 'Gorakhpur Urban', district: 'Gorakhpur' },
  { number: 323, name: 'Gorakhpur Rural', district: 'Gorakhpur' },
  { number: 324, name: 'Sahajanwa', district: 'Gorakhpur' },
  { number: 325, name: 'Khajani', district: 'Gorakhpur', reserved: 'SC' },
  { number: 326, name: 'Chauri-Chaura', district: 'Gorakhpur' },
  { number: 327, name: 'Bansgaon', district: 'Gorakhpur', reserved: 'SC' },
  { number: 328, name: 'Chillupar', district: 'Gorakhpur' },
  { number: 329, name: 'Khadda', district: 'Kushinagar' },
  { number: 330, name: 'Padrauna', district: 'Kushinagar' },
  { number: 331, name: 'Tamkuhi Raj', district: 'Kushinagar' },
  { number: 332, name: 'Fazilnagar', district: 'Kushinagar' },
  { number: 333, name: 'Kushinagar', district: 'Kushinagar' },
  { number: 334, name: 'Hata', district: 'Kushinagar' },
  { number: 335, name: 'Ramkola', district: 'Kushinagar', reserved: 'SC' },
  { number: 336, name: 'Rudrapur', district: 'Deoria' },
  { number: 337, name: 'Deoria', district: 'Deoria' },
  { number: 338, name: 'Pathardeva', district: 'Deoria' },
  { number: 339, name: 'Rampur Karkhana', district: 'Deoria' },
  { number: 340, name: 'Bhatpar Rani', district: 'Deoria' },
  { number: 341, name: 'Salempur', district: 'Deoria', reserved: 'SC' },
  { number: 342, name: 'Barhaj', district: 'Deoria' },
  { number: 343, name: 'Atrauliya', district: 'Azamgarh' },
  { number: 344, name: 'Gopalpur', district: 'Azamgarh' },
  { number: 345, name: 'Sagri', district: 'Azamgarh' },
  { number: 346, name: 'Mubarakpur', district: 'Azamgarh' },
  { number: 347, name: 'Azamgarh', district: 'Azamgarh' },
  { number: 348, name: 'Nizamabad', district: 'Azamgarh' },
  { number: 349, name: 'Phoolpur Pawai', district: 'Azamgarh' },
  { number: 350, name: 'Didarganj', district: 'Azamgarh' },
  { number: 351, name: 'Lalganj', district: 'Azamgarh', reserved: 'SC' },
  { number: 352, name: 'Mehnagar', district: 'Azamgarh', reserved: 'SC' },
  { number: 353, name: 'Madhuban', district: 'Mau' },
  { number: 354, name: 'Ghosi', district: 'Mau' },
  { number: 355, name: 'Muhammadabad-Gohna', district: 'Mau', reserved: 'SC' },
  { number: 356, name: 'Mau', district: 'Mau' },
  { number: 357, name: 'Belthara Road', district: 'Ballia', reserved: 'SC' },
  { number: 358, name: 'Rasara', district: 'Ballia' },
  { number: 359, name: 'Sikanderpur', district: 'Ballia' },
  { number: 360, name: 'Phephana', district: 'Ballia' },
  { number: 361, name: 'Ballia Nagar', district: 'Ballia' },
  { number: 362, name: 'Bansdih', district: 'Ballia' },
  { number: 363, name: 'Bairia', district: 'Ballia' },
  { number: 364, name: 'Badlapur', district: 'Jaunpur' },
  { number: 365, name: 'Shahganj', district: 'Jaunpur' },
  { number: 366, name: 'Jaunpur', district: 'Jaunpur' },
  { number: 367, name: 'Malhani', district: 'Jaunpur' },
  { number: 368, name: 'Mungra Badshahpur', district: 'Jaunpur' },
  { number: 369, name: 'Machhlishahr', district: 'Jaunpur', reserved: 'SC' },
  { number: 370, name: 'Mariyahu', district: 'Jaunpur' },
  { number: 371, name: 'Zafrabad', district: 'Jaunpur' },
  { number: 372, name: 'Kerakat', district: 'Jaunpur', reserved: 'SC' },
  { number: 373, name: 'Jakhanian', district: 'Ghazipur', reserved: 'SC' },
  { number: 374, name: 'Saidpur', district: 'Ghazipur', reserved: 'SC' },
  { number: 375, name: 'Ghazipur Sadar', district: 'Ghazipur' },
  { number: 376, name: 'Jangipur', district: 'Ghazipur' },
  { number: 377, name: 'Zahoorabad', district: 'Ghazipur' },
  { number: 378, name: 'Mohammadabad', district: 'Ghazipur' },
  { number: 379, name: 'Zamania', district: 'Ghazipur' },
  { number: 380, name: 'Mughalsarai', district: 'Chandauli' },
  { number: 381, name: 'Sakaldiha', district: 'Chandauli' },
  { number: 382, name: 'Saiyadraja', district: 'Chandauli' },
  { number: 383, name: 'Chakia', district: 'Chandauli', reserved: 'SC' },
  { number: 384, name: 'Pindra', district: 'Varanasi' },
  { number: 385, name: 'Ajagara', district: 'Varanasi', reserved: 'SC' },
  { number: 386, name: 'Shivpur', district: 'Varanasi' },
  { number: 387, name: 'Rohaniya', district: 'Varanasi' },
  { number: 388, name: 'Varanasi North', district: 'Varanasi' },
  { number: 389, name: 'Varanasi South', district: 'Varanasi' },
  { number: 390, name: 'Varanasi Cantt.', district: 'Varanasi' },
  { number: 391, name: 'Sevapuri', district: 'Varanasi' },
  { number: 392, name: 'Bhadohi', district: 'Bhadohi' },
  { number: 393, name: 'Gyanpur', district: 'Bhadohi' },
  { number: 394, name: 'Aurai', district: 'Bhadohi', reserved: 'SC' },
  { number: 395, name: 'Chhanbey', district: 'Mirzapur', reserved: 'SC' },
  { number: 396, name: 'Mirzapur', district: 'Mirzapur' },
  { number: 397, name: 'Majhawan', district: 'Mirzapur' },
  { number: 398, name: 'Chunar', district: 'Mirzapur' },
  { number: 399, name: 'Marihan', district: 'Mirzapur' },
  { number: 400, name: 'Ghorawal', district: 'Sonbhadra' },
  { number: 401, name: 'Robertsganj', district: 'Sonbhadra' },
  { number: 402, name: 'Obra', district: 'Sonbhadra', reserved: 'ST' },
  { number: 403, name: 'Duddhi', district: 'Sonbhadra', reserved: 'SC' },
];
